CREATE UNIQUE INDEX fd_id_ad_id_x ON jnt_fic_attr USING btree (fd_id, ad_id);
CREATE UNIQUE INDEX fiche_detail_f_id_ad_id ON fiche_detail USING btree (f_id, ad_id);
CREATE INDEX fk_action_person_action_gestion ON action_person USING btree (ag_id);
CREATE INDEX fk_action_person_fiche ON action_person USING btree (f_id);
CREATE INDEX fk_stock_good_repository_r_id ON stock_goods USING btree (r_id);
CREATE INDEX fk_stock_goods_f_id ON stock_goods USING btree (f_id);
CREATE INDEX fk_stock_goods_j_id ON stock_goods USING btree (j_id);
CREATE INDEX fki_f_end_date ON forecast USING btree (f_end_date);
CREATE INDEX fki_f_start_date ON forecast USING btree (f_start_date);
CREATE INDEX fki_jrn_jr_grpt_id ON jrn USING btree (jr_grpt_id);
CREATE INDEX fki_jrnx_f_id ON jrnx USING btree (f_id);
CREATE INDEX fki_jrnx_j_grpt ON jrnx USING btree (j_grpt);
CREATE INDEX fki_profile_menu_me_code ON profile_menu USING btree (me_code);
CREATE INDEX fki_profile_menu_profile ON profile_menu USING btree (p_id);
CREATE INDEX fki_profile_menu_type_fkey ON profile_menu USING btree (p_type_display);
CREATE INDEX idx_qs_internal ON quant_sold USING btree (qs_internal);
CREATE INDEX jnt_fic_att_value_fd_id_idx ON fiche_detail USING btree (f_id);
CREATE INDEX jnt_fic_attr_fd_id_idx ON jnt_fic_attr USING btree (fd_id);
CREATE INDEX jrnx_j_qcode_ix ON jrnx USING btree (j_qcode);
CREATE UNIQUE INDEX k_ag_ref ON action_gestion USING btree (ag_ref);
CREATE INDEX link_action_type_fki ON action_gestion_related USING btree (aga_type);
CREATE UNIQUE INDEX qcode_idx ON fiche_detail USING btree (ad_value) WHERE (ad_id = 23);
CREATE UNIQUE INDEX qf_jr_id ON quant_fin USING btree (jr_id);
CREATE UNIQUE INDEX qp_j_id ON quant_purchase USING btree (j_id);
CREATE UNIQUE INDEX qs_j_id ON quant_sold USING btree (j_id);
CREATE INDEX quant_purchase_jrn_fki ON quant_purchase USING btree (qp_internal);
CREATE INDEX quant_sold_jrn_fki ON quant_sold USING btree (qs_internal);
CREATE UNIQUE INDEX uj_login_uj_jrn_id ON user_sec_jrn USING btree (uj_login, uj_jrn_id);
CREATE UNIQUE INDEX ux_po_name ON poste_analytique USING btree (po_name);
CREATE UNIQUE INDEX x_jrn_jr_id ON jrn USING btree (jr_id);
CREATE INDEX x_mt ON jrn USING btree (jr_mt);
CREATE UNIQUE INDEX x_periode ON parm_periode USING btree (p_start, p_end);
CREATE INDEX x_poste ON jrnx USING btree (j_poste);
