COMMENT ON FUNCTION correct_sequence(p_sequence text, p_col text, p_table text) IS ' Often the primary key is a sequence number and sometimes the value of the sequence is not synchronized with the primary key ( p_sequence : sequence name, p_col : col of the pk,p_table : concerned table';
COMMENT ON FUNCTION html_quote(p_string text) IS 'remove harmfull HTML char';
COMMENT ON TABLE action IS 'The different privileges';
COMMENT ON COLUMN action.ac_code IS 'this code will be used in the code with the function User::check_action ';
COMMENT ON TABLE action_detail IS 'Detail of action_gestion, see class Action_Detail';
COMMENT ON COLUMN action_detail.f_id IS 'the concerned	card';
COMMENT ON COLUMN action_detail.ad_text IS ' Description ';
COMMENT ON COLUMN action_detail.ad_pu IS ' price per unit ';
COMMENT ON COLUMN action_detail.ad_quant IS 'quantity ';
COMMENT ON COLUMN action_detail.ad_tva_id IS ' tva_id ';
COMMENT ON COLUMN action_detail.ad_tva_amount IS ' tva_amount ';
COMMENT ON COLUMN action_detail.ad_total_amount IS ' total amount';
COMMENT ON TABLE action_gestion IS 'Contains the details for the follow-up of customer, supplier, administration';
COMMENT ON COLUMN action_gestion.ag_type IS ' type of action: see document_type ';
COMMENT ON COLUMN action_gestion.f_id_dest IS ' third party ';
COMMENT ON COLUMN action_gestion.ag_title IS ' title ';
COMMENT ON COLUMN action_gestion.ag_timestamp IS ' ';
COMMENT ON COLUMN action_gestion.ag_cal IS ' visible in the calendar if = C';
COMMENT ON COLUMN action_gestion.ag_ref_ag_id IS ' concerning the action ';
COMMENT ON COLUMN action_gestion.ag_comment IS ' comment of the action';
COMMENT ON COLUMN action_gestion.ag_ref IS 'its reference ';
COMMENT ON COLUMN action_gestion.ag_priority IS 'Low, medium, important ';
COMMENT ON COLUMN action_gestion.ag_dest IS ' is the person who has to take care of this action ';
COMMENT ON COLUMN action_gestion.ag_owner IS ' is the owner of this action ';
COMMENT ON COLUMN action_gestion.ag_contact IS ' contact of the third part ';
COMMENT ON COLUMN action_gestion.ag_state IS 'state of the action same as document_state ';
COMMENT ON TABLE attr_def IS 'The available attributs for the cards';
COMMENT ON TABLE attr_min IS 'The value of  attributs for the cards';
COMMENT ON TABLE bilan IS 'contains the template and the data for generating different documents  ';
COMMENT ON COLUMN bilan.b_id IS 'primary key';
COMMENT ON COLUMN bilan.b_name IS 'Name of the document';
COMMENT ON COLUMN bilan.b_file_template IS 'path of the template (document/...)';
COMMENT ON COLUMN bilan.b_file_form IS 'path of the file with forms';
COMMENT ON COLUMN bilan.b_type IS 'type = ODS, RTF...';
COMMENT ON TABLE centralized IS 'The centralized journal';
COMMENT ON TABLE document IS 'This table contains all the documents : summary and lob files';
COMMENT ON TABLE document_modele IS ' contains all the template for the  documents';
COMMENT ON SEQUENCE document_seq IS 'Sequence for the sequence bound to the document modele';
COMMENT ON TABLE document_state IS 'State of the document';
COMMENT ON TABLE document_type IS 'Type of document : meeting, invoice,...';
COMMENT ON TABLE extension IS 'Content the needed information for the extension';
COMMENT ON COLUMN extension.ex_id IS 'Primary key';
COMMENT ON COLUMN extension.ex_name IS 'code of the extension ';
COMMENT ON COLUMN extension.ex_code IS 'code of the extension ';
COMMENT ON COLUMN extension.ex_desc IS 'Description of the extension ';
COMMENT ON COLUMN extension.ex_file IS 'path to the extension to include';
COMMENT ON COLUMN extension.ex_enable IS 'Y : enabled N : disabled ';
COMMENT ON TABLE fiche IS 'Cards';
COMMENT ON TABLE fiche_def IS 'Cards definition';
COMMENT ON TABLE fiche_def_ref IS 'Family Cards definition';
COMMENT ON TABLE forecast IS 'contains the name of the forecast';
COMMENT ON COLUMN forecast_cat.fc_id IS 'primary key';
COMMENT ON COLUMN forecast_cat.fc_desc IS 'text of the category';
COMMENT ON COLUMN forecast_cat.f_id IS 'Foreign key, it is the parent from the table forecast';
COMMENT ON COLUMN forecast_cat.fc_order IS 'Order of the category, used when displaid';
COMMENT ON COLUMN forecast_item.fi_id IS 'Primary key';
COMMENT ON COLUMN forecast_item.fi_text IS 'Label of the i	tem';
COMMENT ON COLUMN forecast_item.fi_account IS 'Accountancy entry';
COMMENT ON COLUMN forecast_item.fi_card IS 'Card (fiche.f_id)';
COMMENT ON COLUMN forecast_item.fi_order IS 'Order of showing (not used)';
COMMENT ON COLUMN forecast_item.fi_amount IS 'Amount';
COMMENT ON COLUMN forecast_item.fi_debit IS 'possible values are D or C';
COMMENT ON COLUMN forecast_item.fi_pid IS '0 for every month, or the value parm_periode.p_id ';
COMMENT ON TABLE form IS 'Forms content';
COMMENT ON TABLE import_tmp IS 'Table temporaire pour l''importation des banques en format CSV';
COMMENT ON COLUMN import_tmp.status IS 'Status w waiting, d delete t transfert';
COMMENT ON TABLE info_def IS 'Contains the types of additionnal info we can add to a operation';
COMMENT ON TABLE jnt_fic_att_value IS 'join between the card and the attribut definition';
COMMENT ON TABLE jnt_fic_attr IS 'join between the family card and the attribut definition';
COMMENT ON TABLE jrn IS 'Journal: content one line for a group of accountancy writing';
COMMENT ON TABLE jrn_action IS 'Possible action when we are in journal (menu)';
COMMENT ON TABLE jrn_def IS 'Definition of a journal, his properties';
COMMENT ON TABLE jrn_rapt IS 'Rapprochement between operation';
COMMENT ON TABLE jrn_type IS 'Type of journal (Sell, Buy, Financial...)';
COMMENT ON TABLE jrnx IS 'Journal: content one line for each accountancy writing';
COMMENT ON TABLE mod_payment IS 'Contains the different media of payment and the corresponding ledger';
COMMENT ON TABLE op_predef IS 'predefined operation';
COMMENT ON COLUMN op_predef.jrn_def_id IS 'jrn_id';
COMMENT ON COLUMN op_predef.od_name IS 'name of the operation';
COMMENT ON TABLE op_predef_detail IS 'contains the detail of predefined operations';
COMMENT ON TABLE operation_analytique IS 'History of the analytic account';
COMMENT ON TABLE parameter IS 'parameter of the company';
COMMENT ON TABLE parm_money IS 'Currency conversion';
COMMENT ON TABLE parm_periode IS 'Periode definition';
COMMENT ON TABLE parm_poste IS 'Contains data for finding is the type of the account (asset)';
COMMENT ON TABLE plan_analytique IS 'Plan Analytique (max 5)';
COMMENT ON TABLE poste_analytique IS 'Poste Analytique';
COMMENT ON TABLE quant_sold IS 'Contains about invoice for customer';
COMMENT ON TABLE stock_goods IS 'About the goods';
COMMENT ON TABLE tmp_pcmn IS 'Plan comptable minimum normalisé';
COMMENT ON TABLE todo_list IS 'Todo list';
COMMENT ON TABLE tva_rate IS 'Rate of vat';
COMMENT ON TABLE user_local_pref IS 'The user''s local parameter ';
COMMENT ON COLUMN user_local_pref.user_id IS 'user''s login ';
COMMENT ON COLUMN user_local_pref.parameter_type IS 'the type of parameter ';
COMMENT ON COLUMN user_local_pref.parameter_value IS 'the value of parameter ';
COMMENT ON TABLE user_sec_extension IS 'Security for extension';
COMMENT ON VIEW vw_fiche_def IS 'all the attributs for	card family';
COMMENT ON TRIGGER action_gestion_t_insert_update ON action_gestion IS 'Truncate the column ag_title to 70 char';
