COMMENT ON COLUMN ac_dossier.dos_email IS 'Max emails per day : 0 none , -1 unlimited or  max value';
COMMENT ON COLUMN ac_users.use_email IS 'Email of the user';
COMMENT ON TABLE dossier_sent_email IS 'Count the sent email by folder';
COMMENT ON COLUMN dossier_sent_email.id IS 'primary key';
COMMENT ON COLUMN dossier_sent_email.de_date IS 'Date YYYYMMDD';
COMMENT ON COLUMN dossier_sent_email.de_sent_email IS 'Number of sent emails';
COMMENT ON COLUMN dossier_sent_email.dos_id IS 'Link to ac_dossier';
COMMENT ON TABLE user_global_pref IS 'The user''s global parameter ';
COMMENT ON COLUMN user_global_pref.user_id IS 'user''s login ';
COMMENT ON COLUMN user_global_pref.parameter_type IS 'the type of parameter ';
COMMENT ON COLUMN user_global_pref.parameter_value IS 'the value of parameter ';
