<?php 

/**
 * Autogenerated file 
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
require_once NOALYSS_INCLUDE.'/lib/noalyss_sql.class.php';
require_once NOALYSS_INCLUDE.'/lib/database.class.php';


/**
 * class_parm_periode_sql.php
 *
 *@file
 *@brief Manage the table public.parm_periode
 */

/**
 * *@brief Manage the table public.parm_periode
 */
class Parm_periode_SQL extends Noalyss_SQL
{

function __construct(Database $p_cn,$p_id=-1)
  {
  $this->table = "public.parm_periode";
  $this->primary_key = "p_id";
/*
 * List of columns
 */
  $this->name=array(
  	"p_id"=>"p_id"
	,"p_start"=>"p_start"
	,"p_end"=>"p_end"
	,"p_exercice"=>"p_exercice"
	,"p_closed"=>"p_closed"
	,"p_central"=>"p_central"
        );
/*
 * Type of columns
 */
  $this->type = array(
   	"p_id"=>"numeric"
	,"p_start"=>"date"
	,"p_end"=>"date"
	,"p_exercice"=>"text"
	,"p_closed"=>"boolean"
	,"p_central"=>"boolean"
          );
 

  $this->default = array(
  "p_id" => "auto"
  );

  $this->date_format = "DD.MM.YYYY";
  parent::__construct($p_cn,$p_id);
  }
  

}