<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:23:53.
 */
class Document_ExportTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Document_Export
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new Document_Export;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Document_Export::concatenate_pdf
     * @todo   Implement testConcatenate_pdf().
     */
    public function testConcatenate_pdf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Document_Export::move_file
     * @todo   Implement testMove_file().
     */
    public function testMove_file()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Document_Export::send_pdf
     * @todo   Implement testSend_pdf().
     */
    public function testSend_pdf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Document_Export::clean_folder
     * @todo   Implement testClean_folder().
     */
    public function testClean_folder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Document_Export::export_all
     * @todo   Implement testExport_all().
     */
    public function testExport_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Document_Export::check_file
     * @todo   Implement testCheck_file().
     */
    public function testCheck_file()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
