<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-07 at 23:05:36.
 * @backupGlobals enabled
 */
require 'global.php';
class FicheTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Fiche
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Fiche::cmp_name
     * @todo   Implement testCmp_name().
     */
    public function testCmp_name()
    {
       
    }

    /**
     * @covers Fiche::get_bk_account
     * @todo   Implement testGet_bk_account().
     */
    public function testGet_bk_account()
    {
     include 'global.php';
     $this->object=new Fiche($g_connection);
     $result=$this->object->get_bk_account();
     $this->assertEquals(gettype($result),'array');
     $count = count($result);
     $this->assertGreaterThan(0,$count);
     
    }

    /**
     * @covers Fiche::get_by_qcode
     * @todo   Implement testGet_by_qcode().
     */
    public function testGet_by_qcode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::setAttribut
     * @todo   Implement testSetAttribut().
     */
    public function testSetAttribut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::getAttribut
     * @todo   Implement testGetAttribut().
     */
    public function testGetAttribut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::seek
     * @todo   Implement testSeek().
     */
    public function testSeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::size
     * @todo   Implement testSize().
     */
    public function testSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::count_by_modele
     * @todo   Implement testCount_by_modele().
     */
    public function testCount_by_modele()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::GetByDef
     * @todo   Implement testGetByDef().
     */
    public function testGetByDef()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::ShowTable
     * @todo   Implement testShowTable().
     */
    public function testShowTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::strAttribut
     * @todo   Implement testStrAttribut().
     */
    public function testStrAttribut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::to_array
     * @todo   Implement testTo_array().
     */
    public function testTo_array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::blank
     * @todo   Implement testBlank().
     */
    public function testBlank()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::Display
     * @todo   Implement testDisplay().
     */
    public function testDisplay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::Save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::insert
     * @todo   Implement testInsert().
     */
    public function testInsert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_quick_code
     * @todo   Implement testGet_quick_code().
     */
    public function testGet_quick_code()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::Get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_by_category
     * @todo   Implement testGet_by_category().
     */
    public function testGet_by_category()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_fiche_def_ref_id
     * @todo   Implement testGet_fiche_def_ref_id().
     */
    public function testGet_fiche_def_ref_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_row_date
     * @todo   Implement testGet_row_date().
     */
    public function testGet_row_date()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_row
     * @todo   Implement testGet_row().
     */
    public function testGet_row()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::HtmlTableDetail
     * @todo   Implement testHtmlTableDetail().
     */
    public function testHtmlTableDetail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::HtmlTable
     * @todo   Implement testHtmlTable().
     */
    public function testHtmlTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::HtmlTableHeader
     * @todo   Implement testHtmlTableHeader().
     */
    public function testHtmlTableHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_solde_detail
     * @todo   Implement testGet_solde_detail().
     */
    public function testGet_solde_detail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_bk_balance
     * @todo   Implement testGet_bk_balance().
     */
    public function testGet_bk_balance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::empty_attribute
     * @todo   Implement testEmpty_attribute().
     */
    public function testEmpty_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::Summary
     * @todo   Implement testSummary().
     */
    public function testSummary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_categorie
     * @todo   Implement testGet_categorie().
     */
    public function testGet_categorie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::belong_ledger
     * @todo   Implement testBelong_ledger().
     */
    public function testBelong_ledger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_fiche_def
     * @todo   Implement testGet_fiche_def().
     */
    public function testGet_fiche_def()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::is_used
     * @todo   Implement testIs_used().
     */
    public function testIs_used()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::build_sql
     * @todo   Implement testBuild_sql().
     */
    public function testBuild_sql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::move_to
     * @todo   Implement testMove_to().
     */
    public function testMove_to()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_amount_side
     * @todo   Implement testGet_amount_side().
     */
    public function testGet_amount_side()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::test_me
     * @todo   Implement testTest_me().
     */
    public function testTest_me()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_gestion_title
     * @todo   Implement testGet_gestion_title().
     */
    public function testGet_gestion_title()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fiche::get_all_account
     * @todo   Implement testGet_all_account().
     */
    public function testGet_all_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
