<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-07 at 23:05:35.
 */
class Follow_UpTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Follow_Up
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new Follow_Up;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Follow_Up::sql_security_filter
     * @todo   Implement testSql_security_filter().
     */
    public function testSql_security_filter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::Display
     * @todo   Implement testDisplay().
     */
    public function testDisplay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::myList
     * @todo   Implement testMyList().
     */
    public function testMyList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::Update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::generate_document
     * @todo   Implement testGenerate_document().
     */
    public function testGenerate_document()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::fromArray
     * @todo   Implement testFromArray().
     */
    public function testFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::get_last
     * @todo   Implement testGet_last().
     */
    public function testGet_last()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::get_today
     * @todo   Implement testGet_today().
     */
    public function testGet_today()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::get_late
     * @todo   Implement testGet_late().
     */
    public function testGet_late()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::insert_operation
     * @todo   Implement testInsert_operation().
     */
    public function testInsert_operation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::remove_operation_deprecated
     * @todo   Implement testRemove_operation_deprecated().
     */
    public function testRemove_operation_deprecated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::display_search
     * @todo   Implement testDisplay_search().
     */
    public function testDisplay_search()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::show_action_list
     * @todo   Implement testShow_action_list().
     */
    public function testShow_action_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::filter_by_tag
     * @todo   Implement testFilter_by_tag().
     */
    public function testFilter_by_tag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::create_query
     * @todo   Implement testCreate_query().
     */
    public function testCreate_query()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::short_list
     * @todo   Implement testShort_list().
     */
    public function testShort_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::insert_action
     * @todo   Implement testInsert_action().
     */
    public function testInsert_action()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::export_csv
     * @todo   Implement testExport_csv().
     */
    public function testExport_csv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::get_all_operation
     * @todo   Implement testGet_all_operation().
     */
    public function testGet_all_operation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::tag_get
     * @todo   Implement testTag_get().
     */
    public function testTag_get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::tag_add
     * @todo   Implement testTag_add().
     */
    public function testTag_add()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::tag_remove
     * @todo   Implement testTag_remove().
     */
    public function testTag_remove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::tag_cell
     * @todo   Implement testTag_cell().
     */
    public function testTag_cell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::action_tag_remove
     * @todo   Implement testAction_tag_remove().
     */
    public function testAction_tag_remove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::action_tag_add
     * @todo   Implement testAction_tag_add().
     */
    public function testAction_tag_add()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::action_tag_clear
     * @todo   Implement testAction_tag_clear().
     */
    public function testAction_tag_clear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::action_print
     * @todo   Implement testAction_print().
     */
    public function testAction_print()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::tag_clear
     * @todo   Implement testTag_clear().
     */
    public function testTag_clear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::action_set_state
     * @todo   Implement testAction_set_state().
     */
    public function testAction_set_state()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Follow_Up::action_remove
     * @todo   Implement testAction_remove().
     */
    public function testAction_remove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
