<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-09 at 12:39:58.
 */
class Acc_LedgerTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Acc_Ledger
     */
    protected $object;
           protected function getDataSet()
    {
        $dataSet = new PHPUnit_Extensions_Database_DataSet_CsvDataSet();
        $dataSet->addTable('jrn', dirname(__FILE__)."/jrn.csv");
        return $dataSet;
    }
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        include 'global.php';
        $this->object=new Acc_Ledger($g_connection,0);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Acc_Ledger::get_last_pj
     * @todo   Implement testGet_last_pj().
     */
    public function testGet_last_pj()
    {   
 
        $this->object->id=1;
        $array=$this->object->get_last(2);
        $this->assertEquals(2,count($array));
        
    }

    /**
     * @covers Acc_Ledger::get_type
     * @todo   Implement testGet_type().
     */
    public function testGet_type()
    {
        $this->object->id=0;
        $type=$this->object->get_type();
        $this->assertEquals('GL',$type);
        
         $this->object->id=1;
        $type=$this->object->get_type();
        $this->assertEquals('FIN',$type);
        
         $this->object->id=2;
        $type=$this->object->get_type();
        $this->assertEquals('VEN',$type);
        
         $this->object->id=3;
        $type=$this->object->get_type();
        $this->assertEquals('ACH',$type);
    }

    /**
     * @covers Acc_Ledger::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        $this->object->delete();
    }

    /**
     * @covers Acc_Ledger::display_warning
     * @todo   Implement testDisplay_warning().
     */
    public function testDisplay_warning()
    {
        $this->object->display_warning("Alert", "warning");
    }

    /**
     * @covers Acc_Ledger::reverse
     * @todo   Implement testReverse().
     */
    public function testReverse()
    {
        $this->object->reverse('01.01.2014');
    }

    /**
     * @covers Acc_Ledger::get_name
     * @todo   Implement testGet_name().
     */
    public function testGet_name()
    {
        $this->object->id=3;
        $name=$this->object->get_name();
        $this->assertEquals('Achat',$name);
    }

    /**
     * @covers Acc_Ledger::get_row
     * @todo   Implement testGet_row().
     */
    public function testGet_row()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_rowSimple
     * @todo   Implement testGet_rowSimple().
     */
    public function testGet_rowSimple()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::guess_pj
     * @todo   Implement testGuess_pj().
     */
    public function testGuess_pj()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::list_operation_to_reconcile
     * @todo   Implement testList_operation_to_reconcile().
     */
    public function testList_operation_to_reconcile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::list_operation
     * @todo   Implement testList_operation().
     */
    public function testList_operation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_detail
     * @todo   Implement testGet_detail().
     */
    public function testGet_detail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_propertie
     * @todo   Implement testGet_propertie().
     */
    public function testGet_propertie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::GetDefLine
     * @todo   Implement testGetDefLine().
     */
    public function testGetDefLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_solde
     * @todo   Implement testGet_solde().
     */
    public function testGet_solde()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::select_ledger
     * @todo   Implement testSelect_ledger().
     */
    public function testSelect_ledger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_fiche_def
     * @todo   Implement testGet_fiche_def().
     */
    public function testGet_fiche_def()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_class_def
     * @todo   Implement testGet_class_def().
     */
    public function testGet_class_def()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::confirm
     * @todo   Implement testConfirm().
     */
    public function testConfirm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_min_row
     * @todo   Implement testGet_min_row().
     */
    public function testGet_min_row()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::input
     * @todo   Implement testInput().
     */
    public function testInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::is_closed
     * @todo   Implement testIs_closed().
     */
    public function testIs_closed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::verify
     * @todo   Implement testVerify().
     */
    public function testVerify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::compute_internal_code
     * @todo   Implement testCompute_internal_code().
     */
    public function testCompute_internal_code()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_request
     * @todo   Implement testGet_request().
     */
    public function testGet_request()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::next_number
     * @todo   Implement testNext_number().
     */
    public function testNext_number()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_first
     * @todo   Implement testGet_first().
     */
    public function testGet_first()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::update_paid
     * @todo   Implement testUpdate_paid().
     */
    public function testUpdate_paid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::update_internal_code
     * @todo   Implement testUpdate_internal_code().
     */
    public function testUpdate_internal_code()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_default_card
     * @todo   Implement testGet_default_card().
     */
    public function testGet_default_card()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_all_fiche_def
     * @todo   Implement testGet_all_fiche_def().
     */
    public function testGet_all_fiche_def()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_saldo_exercice
     * @todo   Implement testGet_saldo_exercice().
     */
    public function testGet_saldo_exercice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::check_strict
     * @todo   Implement testCheck_strict().
     */
    public function testCheck_strict()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::check_periode
     * @todo   Implement testCheck_periode().
     */
    public function testCheck_periode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_last_date
     * @todo   Implement testGet_last_date().
     */
    public function testGet_last_date()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_id
     * @todo   Implement testGet_id().
     */
    public function testGet_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::create_document
     * @todo   Implement testCreate_document().
     */
    public function testCreate_document()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::check_payment
     * @todo   Implement testCheck_payment().
     */
    public function testCheck_payment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::inc_seq_pj
     * @todo   Implement testInc_seq_pj().
     */
    public function testInc_seq_pj()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::search_form
     * @todo   Implement testSearch_form().
     */
    public function testSearch_form()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::build_search_sql
     * @todo   Implement testBuild_search_sql().
     */
    public function testBuild_search_sql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::display_search_form
     * @todo   Implement testDisplay_search_form().
     */
    public function testDisplay_search_form()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_last
     * @todo   Implement testGet_last().
     */
    public function testGet_last()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::search_group
     * @todo   Implement testSearch_group().
     */
    public function testSearch_group()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_operation
     * @todo   Implement testGet_operation().
     */
    public function testGet_operation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::existing_vat
     * @todo   Implement testExisting_vat().
     */
    public function testExisting_vat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_other_amount
     * @todo   Implement testGet_other_amount().
     */
    public function testGet_other_amount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::vat_operation
     * @todo   Implement testVat_operation().
     */
    public function testVat_operation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::previous_amount
     * @todo   Implement testPrevious_amount().
     */
    public function testPrevious_amount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::test_me
     * @todo   Implement testTest_me().
     */
    public function testTest_me()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::array_cat
     * @todo   Implement testArray_cat().
     */
    public function testArray_cat()
    {
        $array=Acc_Ledger::array_cat();
        $this->assertEquals(4,count($array));
    }

    /**
     * @covers Acc_Ledger::get_tiers
     * @todo   Implement testGet_tiers().
     */
    public function testGet_tiers()
    {
        $this->object->get_tiers($p_jrn_type, $jr_id);
    }

    /**
     * @covers Acc_Ledger::listing
     * @todo   Implement testListing().
     */
    public function testListing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::display_ledger
     * @todo   Implement testDisplay_ledger().
     */
    public function testDisplay_ledger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::verify_ledger
     * @todo   Implement testVerify_ledger().
     */
    public function testVerify_ledger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::input_paid
     * @todo   Implement testInput_paid().
     */
    public function testInput_paid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::input_new
     * @todo   Implement testInput_new().
     */
    public function testInput_new()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::save_new
     * @todo   Implement testSave_new().
     */
    public function testSave_new()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::delete_ledger
     * @todo   Implement testDelete_ledger().
     */
    public function testDelete_ledger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_operation_date
     * @todo   Implement testGet_operation_date().
     */
    public function testGet_operation_date()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_supplier_now
     * @todo   Implement testGet_supplier_now().
     */
    public function testGet_supplier_now()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_supplier_late
     * @todo   Implement testGet_supplier_late().
     */
    public function testGet_supplier_late()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_customer_now
     * @todo   Implement testGet_customer_now().
     */
    public function testGet_customer_now()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::get_customer_late
     * @todo   Implement testGet_customer_late().
     */
    public function testGet_customer_late()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger::convert_from_follow
     * @todo   Implement testConvert_from_follow().
     */
    public function testConvert_from_follow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
