<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:23:53.
 */
class HtmlInputTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var HtmlInput
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new HtmlInput;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers HtmlInput::setReadOnly
     * @todo   Implement testSetReadOnly().
     */
    public function testSetReadOnly()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::set_attribute
     * @todo   Implement testSet_attribute().
     */
    public function testSet_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::get_js_attr
     * @todo   Implement testGet_js_attr().
     */
    public function testGet_js_attr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::make_object
     * @todo   Implement testMake_object().
     */
    public function testMake_object()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::debug
     * @todo   Implement testDebug().
     */
    public function testDebug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::submit
     * @todo   Implement testSubmit().
     */
    public function testSubmit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::button
     * @todo   Implement testButton().
     */
    public function testButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::reset
     * @todo   Implement testReset().
     */
    public function testReset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::hidden
     * @todo   Implement testHidden().
     */
    public function testHidden()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::extension
     * @todo   Implement testExtension().
     */
    public function testExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::button_anchor
     * @todo   Implement testButton_anchor().
     */
    public function testButton_anchor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::infobulle
     * @todo   Implement testInfobulle().
     */
    public function testInfobulle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::warnbulle
     * @todo   Implement testWarnbulle().
     */
    public function testWarnbulle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::detail_op
     * @todo   Implement testDetail_op().
     */
    public function testDetail_op()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::detail_action
     * @todo   Implement testDetail_action().
     */
    public function testDetail_action()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::detail_modele_document
     * @todo   Implement testDetail_modele_document().
     */
    public function testDetail_modele_document()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::remove_stock
     * @todo   Implement testRemove_stock().
     */
    public function testRemove_stock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::history_card
     * @todo   Implement testHistory_card().
     */
    public function testHistory_card()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::history_card_button
     * @todo   Implement testHistory_card_button().
     */
    public function testHistory_card_button()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::history_account
     * @todo   Implement testHistory_account().
     */
    public function testHistory_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::select_ledger
     * @todo   Implement testSelect_ledger().
     */
    public function testSelect_ledger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::select_cat
     * @todo   Implement testSelect_cat().
     */
    public function testSelect_cat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::display_periode
     * @todo   Implement testDisplay_periode().
     */
    public function testDisplay_periode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::button_close
     * @todo   Implement testButton_close().
     */
    public function testButton_close()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::anchor_close
     * @todo   Implement testAnchor_close().
     */
    public function testAnchor_close()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::button_action
     * @todo   Implement testButton_action().
     */
    public function testButton_action()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::button_image
     * @todo   Implement testButton_image().
     */
    public function testButton_image()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::anchor_hide
     * @todo   Implement testAnchor_hide().
     */
    public function testAnchor_hide()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::print_window
     * @todo   Implement testPrint_window().
     */
    public function testPrint_window()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::card_detail
     * @todo   Implement testCard_detail().
     */
    public function testCard_detail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::array_to_hidden
     * @todo   Implement testArray_to_hidden().
     */
    public function testArray_to_hidden()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::get_to_hidden
     * @todo   Implement testGet_to_hidden().
     */
    public function testGet_to_hidden()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::post_to_hidden
     * @todo   Implement testPost_to_hidden().
     */
    public function testPost_to_hidden()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::request_to_hidden
     * @todo   Implement testRequest_to_hidden().
     */
    public function testRequest_to_hidden()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::array_to_string
     * @todo   Implement testArray_to_string().
     */
    public function testArray_to_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::get_to_string
     * @todo   Implement testGet_to_string().
     */
    public function testGet_to_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::post_to_string
     * @todo   Implement testPost_to_string().
     */
    public function testPost_to_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::request_to_string
     * @todo   Implement testRequest_to_string().
     */
    public function testRequest_to_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::generate_id
     * @todo   Implement testGenerate_id().
     */
    public function testGenerate_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::default_value
     * @todo   Implement testDefault_value().
     */
    public function testDefault_value()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::default_value_get
     * @todo   Implement testDefault_value_get().
     */
    public function testDefault_value_get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::default_value_post
     * @todo   Implement testDefault_value_post().
     */
    public function testDefault_value_post()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::default_value_request
     * @todo   Implement testDefault_value_request().
     */
    public function testDefault_value_request()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::title_box
     * @todo   Implement testTitle_box().
     */
    public function testTitle_box()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::anchor
     * @todo   Implement testAnchor().
     */
    public function testAnchor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::select_stock
     * @todo   Implement testSelect_stock().
     */
    public function testSelect_stock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::filter_table
     * @todo   Implement testFilter_table().
     */
    public function testFilter_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::show_reconcile
     * @todo   Implement testShow_reconcile().
     */
    public function testShow_reconcile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::calendar_zoom
     * @todo   Implement testCalendar_zoom().
     */
    public function testCalendar_zoom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::button_choice_ledger
     * @todo   Implement testButton_choice_ledger().
     */
    public function testButton_choice_ledger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtmlInput::show_receipt_document
     * @todo   Implement testShow_receipt_document().
     */
    public function testShow_receipt_document()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
