<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:23:52.
 */
class Anc_OperationTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Anc_Operation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new Anc_Operation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Anc_Operation::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::get_list
     * @todo   Implement testGet_list().
     */
    public function testGet_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::html_table
     * @todo   Implement testHtml_table().
     */
    public function testHtml_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::get_by_jid
     * @todo   Implement testGet_by_jid().
     */
    public function testGet_by_jid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::update_from_jrnx
     * @todo   Implement testUpdate_from_jrnx().
     */
    public function testUpdate_from_jrnx()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::get_jrid
     * @todo   Implement testGet_jrid().
     */
    public function testGet_jrid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::get_balance
     * @todo   Implement testGet_balance().
     */
    public function testGet_balance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::display_form_plan
     * @todo   Implement testDisplay_form_plan().
     */
    public function testDisplay_form_plan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::save_form_plan_vat_nd
     * @todo   Implement testSave_form_plan_vat_nd().
     */
    public function testSave_form_plan_vat_nd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::save_form_plan
     * @todo   Implement testSave_form_plan().
     */
    public function testSave_form_plan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::save_update_form
     * @todo   Implement testSave_update_form().
     */
    public function testSave_update_form()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::to_request
     * @todo   Implement testTo_request().
     */
    public function testTo_request()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::delete_by_jid
     * @todo   Implement testDelete_by_jid().
     */
    public function testDelete_by_jid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::display_table
     * @todo   Implement testDisplay_table().
     */
    public function testDisplay_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Operation::test_me
     * @todo   Implement testTest_me().
     */
    public function testTest_me()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
