<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:26:55.
 */
class StockTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Stock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new Stock;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Stock::history
     * @todo   Implement testHistory().
     */
    public function testHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stock::export_stock_histo_form
     * @todo   Implement testExport_stock_histo_form().
     */
    public function testExport_stock_histo_form()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stock::export_stock_summary_list_form
     * @todo   Implement testExport_stock_summary_list_form().
     */
    public function testExport_stock_summary_list_form()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stock::search_box_button
     * @todo   Implement testSearch_box_button().
     */
    public function testSearch_box_button()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stock::search_box
     * @todo   Implement testSearch_box().
     */
    public function testSearch_box()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stock::create_query_histo
     * @todo   Implement testCreate_query_histo().
     */
    public function testCreate_query_histo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stock::summary
     * @todo   Implement testSummary().
     */
    public function testSummary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stock::build_tmp_table
     * @todo   Implement testBuild_tmp_table().
     */
    public function testBuild_tmp_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
