<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:20:36.
 * @backupGlobals enabled
 */
class Acc_Ledger_PurchaseTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Acc_Ledger_Purchase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        include 'global.php';
        $this->object=new Acc_Ledger_Purchase($g_connection,3);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Acc_Ledger_Purchase::verify
     * @todo   Implement testVerify().
     * @expectedException Exception
     */
    public function testVerify()
    {
        $this->object->verify(array());
    }

    /**
     * @covers Acc_Ledger_Purchase::insert
     * @todo   Implement testInsert().
     */
    public function testInsert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger_Purchase::input
     * @todo   Implement testInput().
     */
    public function testInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger_Purchase::confirm
     * @todo   Implement testConfirm().
     */
    public function testConfirm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger_Purchase::extra_info
     * @todo   Implement testExtra_info().
     */
    public function testExtra_info()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger_Purchase::show_unpaid
     * @todo   Implement testShow_unpaid().
     */
    public function testShow_unpaid()
    {
       // OBSOLETE : function must be removed in the next code cleaning
       //  $str_html=$this->object->show_unpaid();
        
    }

    /**
     * @covers Acc_Ledger_Purchase::get_detail_purchase
     * @todo   Implement testGet_detail_purchase().
     */
    public function testGet_detail_purchase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger_Purchase::heading_detail_purchase
     * @todo   Implement testHeading_detail_purchase().
     */
    public function testHeading_detail_purchase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
