<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:28:11.
 */
class Stock_SqlTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Stock_Sql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Stock_Sql;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
