<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:25:44.
 */
class Menu_Ref_SQLTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Menu_Ref_SQL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new Menu_Ref_SQL;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Menu_Ref_SQL::test_me
     * @todo   Implement testTest_me().
     */
    public function testTest_me()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
