#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

ynh_backup_before_upgrade
ynh_clean_setup () {
    ynh_restore_upgradebackup
}
ynh_abort_if_errors

#save database qnd config before replace all files
sudo -i -u postgres
pg_dumpall > noalyss_backup.dmp
sudo cp -a noalyss/include/config.inc.php etc/tmp/


#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
