<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:20:37.
 * @backupGlobals enabled
 */
class Acc_Ledger_SoldTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Acc_Ledger_Sold
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        include 'global.php';
        $this->object=new Acc_Ledger_Sold($g_connection, 2);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Acc_Ledger_Sold::verify
     * @todo   Implement testVerify().
     * @expectedException Exception
     */
    public function testVerify()
    {
        $this->object->verify(array());
    }

    /**
     * @covers Acc_Ledger_Sold::insert
     * @todo   Implement testInsert().
     * @expectedException Exception
     */
    public function testInsert()
    {
        $this->object->insert(array());
    }

    /**
     * @covers Acc_Ledger_Sold::confirm
     * @todo   Implement testConfirm().
     * @expectedException Exception
     */
    public function testConfirm()
    {
        $_POST['p_jrn']=$this->object->id;
        $this->object->confirm(array());
    }

    /**
     * @covers Acc_Ledger_Sold::extra_info
     * @todo   Implement testExtra_info().
     */
    public function testExtra_info()
    {
        $info=$this->object->extra_info();
        if (!is_string($info))
        {
            $this->assertTrue(FALSE);
        }
    }

    /**
     * @covers Acc_Ledger_Sold::show_unpaid
     * @todo   Implement testShow_unpaid().
     */
    public function testShow_unpaid()
    {
        // OBSOLETE : must be removed
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger_Sold::input
     * @todo   Implement testInput().
     */
    public function testInput()
    {
        $_REQUEST['ac']='VEN';
        $info=$this->object->input();
        if (!is_string($info))
        {
            $this->assertTrue(FALSE);
        }
    }

    /**
     * @covers Acc_Ledger_Sold::get_detail_sale
     * @todo   Implement testGet_detail_sale().
     */
    public function testGet_detail_sale()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Acc_Ledger_Sold::heading_detail_sale
     * @todo   Implement testHeading_detail_sale().
     */
    public function testHeading_detail_sale()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
