<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:23:52.
 */
class Anc_KeyTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Anc_Key
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new Anc_Key;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Anc_Key::key_avaiable
     * @todo   Implement testKey_avaiable().
     */
    public function testKey_avaiable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Key::display_choice
     * @todo   Implement testDisplay_choice().
     */
    public function testDisplay_choice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Key::display_list
     * @todo   Implement testDisplay_list().
     */
    public function testDisplay_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Key::input
     * @todo   Implement testInput().
     */
    public function testInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Key::verify
     * @todo   Implement testVerify().
     */
    public function testVerify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Key::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Key::fill_table
     * @todo   Implement testFill_table().
     */
    public function testFill_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Key::key_add
     * @todo   Implement testKey_add().
     */
    public function testKey_add()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_Key::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
