<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:23:52.
 */
class Anc_Key_Detail_SQLTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Anc_Key_Detail_SQL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @backupGlobals enabled
     */
    protected function setUp()
    {
        include 'global.php';
        $this->object=new Anc_Key_Detail_SQL($g_connection);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @backupGlobals enabled
     * 
     */
    function test_me()
    {
        $this->assertTrue(true);
    }

}
