<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 14:23:51.
 */
class Anc_GrandLivreTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Anc_GrandLivre
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new Anc_GrandLivre;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Anc_GrandLivre::set_sql_filter
     * @todo   Implement testSet_sql_filter().
     */
    public function testSet_sql_filter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_GrandLivre::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_GrandLivre::load_csv
     * @todo   Implement testLoad_csv().
     */
    public function testLoad_csv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_GrandLivre::button_export_pdf
     * @todo   Implement testButton_export_pdf().
     */
    public function testButton_export_pdf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_GrandLivre::display_html
     * @todo   Implement testDisplay_html().
     */
    public function testDisplay_html()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_GrandLivre::show_button
     * @todo   Implement testShow_button().
     */
    public function testShow_button()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anc_GrandLivre::display_csv
     * @todo   Implement testDisplay_csv().
     */
    public function testDisplay_csv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
