<?php 
$menu[]=_('Achat');  $desc[]=_('Nouvel achat ou dépense');$desc_long[]=_('Vous permet d\'encoder des achats, dépenses, des notes de frais ou des notes de crédits, vous pouvez spécifier un bénéficiaire ou un autre moyen de paiement');
$menu[]=_('Historique');  $desc[]=_('Historique des imputations analytiques');$desc_long[]=_('Historique des imputations analytiques');
$menu[]=_('Balance simple');  $desc[]=_('Balance simple des imputations analytiques');$desc_long[]=_('Balance simple des imputations analytiques');
$menu[]=_('Tableau');  $desc[]=_('Tableau lié à la comptabilité');$desc_long[]=_('Tableau lié à la comptabilité');
$menu[]=_('Balance Analytique/comptabilité');  $desc[]=_('Lien entre comptabilité et Comptabilité analytique');$desc_long[]=_('Lien entre comptabilité et Comptabilité analytique');
$menu[]=_('Groupe');  $desc[]=_('Balance par groupe');$desc_long[]=_('Balance par groupe');
$menu[]=_('TVA');  $desc[]=_('Config. de la tva');$desc_long[]=_('Permet d\'ajouter des taux de TVA ou de les modifier ainsi que les postes comptables de ces TVA, ces TVA sont utilisables dans les menus de vente et d\'achat');
$menu[]=_('Vente');  $desc[]=_('Nouvelle vente ou recette');$desc_long[]=_('Encodage de tous vos revenus ou vente');
$menu[]=_('Config. Menu');  $desc[]=_('Configuration des menus et plugins');$desc_long[]=_('Ajout de menu ou de plugins');
$menu[]=_('Fournisseur');  $desc[]=_('Suivi fournisseur');$desc_long[]=_('Suivi des fournisseurs : devis, lettres, email....');
$menu[]=_('Opérations diverses');  $desc[]=_('OD analytique');$desc_long[]=_('Opérations diverses en Analytique');
$menu[]=_('Création de rapport');  $desc[]=_('Création de rapport');$desc_long[]=_('Création de rapport sur mesure, comme les ratios, vous permet de créer des graphiques de vos données (vente, achat...)');
$menu[]=_('saut de ligne');  
$menu[]=_('Client');  $desc[]=_('Suivi client');$desc_long[]=_('Suivi client : devis, réunion, courrier, commande...');
$menu[]=_('Historique stock');  
$menu[]=_('Export Historique');  
$menu[]=_('Export Journaux');  
$menu[]=_('Export Journaux');  
$menu[]=_('Export Poste détail');  
$menu[]=_('Export Poste détail');  
$menu[]=_('Export Fiche détail');  
$menu[]=_('Export Fiche détail');  
$menu[]=_('Export Fiche balance');  
$menu[]=_('Export Fiche balance');  
$menu[]=_('Export report');  
$menu[]=_('Export report');  
$menu[]=_('Export Fiche');  
$menu[]=_('Export Fiche');  
$menu[]=_('Export Grand Livre');  
$menu[]=_('Export Grand Livre');  
$menu[]=_('Export Sécurité');  
$menu[]=_('Export Comptabilité analytique');  
$menu[]=_('Export Comptabilité analytique balance simple');  
$menu[]=_('Export Comptabilité analytique');  
$menu[]=_('Export Comptabilité analytique balance double');  
$menu[]=_('Export Comptabilité analytique balance double');  
$menu[]=_('Export Balance comptable');  
$menu[]=_('Export Balance comptable');  
$menu[]=_('Export Tableau Analytique');  
$menu[]=_('Export Historique Compt. Analytique');  
$menu[]=_('Export Balance groupe analytique');  
$menu[]=_('Export Bilan');  
$menu[]=_('Impression Grand-Livre');  
$menu[]=_('Export définition d\'un raport');  
$menu[]=_('Export Action Gestion');  
$menu[]=_('Export Historique mouvement stock');  
$menu[]=_('Export Résumé list stock');  
$menu[]=_('Extension');  $desc[]=_('Extensions (plugins)');$desc_long[]=_('Menu regroupant les plugins');
$menu[]=_('Plan Compt. analytique');  $desc[]=_('Plan analytique');$desc_long[]=_('Axe analytique');
$menu[]=_('Groupe');  $desc[]=_('Groupe analytique');$desc_long[]=_('Regroupement de compte analytique');
$menu[]=_('Contact');  $desc[]=_('Liste des contacts');$desc_long[]=_('Liste de tous vos contacts');
$menu[]=_('Ecriture prédefinie');  $desc[]=_('Gestion des opérations prédéfinifies');$desc_long[]=_('Les opérations prédéfinies sont des opérations que vous faites régulièrement (loyer, abonnement,...) ');
$menu[]=_('Opérations Diverses');  $desc[]=_('Nouvelle opérations diverses');$desc_long[]=_('Opération diverses tels que les amortissements, les augmentations de capital, les salaires, ...');
$menu[]=_('Nouvel extrait');  $desc[]=_('Nouvel extrait bancaire');$desc_long[]=_('Encodage d\'un extrait bancaire (=relevé bancaire)');
$menu[]=_('Recherche');  $desc[]=_('Recherche');$desc_long[]=_('Historique de toutes vos opérations un menu de recherche dans une nouvelle fenêtre, vous permettra de retrouver rapidement l\'opération qui vous intéresse');
$menu[]=_('Paramètre');  $desc[]=_('Module paramètre');$desc_long[]=_('Module paramètres');
$menu[]=_('Catégorie de documents');  $desc[]=_('Config. catégorie de documents');$desc_long[]=_('Vous permet d\'ajouter de nouveaux type de documents (bordereau de livraison, devis..)');
$menu[]=_('Lettrage par Fiche');  $desc[]=_('Lettrage par fiche');$desc_long[]=_('Lettrage par fiche');
$menu[]=_('Historique achat');  $desc[]=_('Historique achat');$desc_long[]=_('Historique de toutes vos opérations dans les journaux d\'achats un menu de recherche, vous permettra de retrouver rapidement l\'opération qui vous intéresse');
$menu[]=_('Historique opérations diverses');  $desc[]=_('Historique opérations diverses');$desc_long[]=_('Historique de toutes vos opérations dans les journaux d\'opérations diverses un menu de recherche, vous permettra de retrouver rapidement l\'opération qui vous intéresse');
$menu[]=_('Poste');  $desc[]=_('Impression du détail d\'un poste comptable');$desc_long[]=_('Impression du détail d\'un poste comptable');
$menu[]=_('Rapport');  $desc[]=_('Impression de rapport');$desc_long[]=_('Impression de rapport personnalisé, il est aussi possible d\'exporter en CSV afin de faire des graphiques');
$menu[]=_('Grand Livre');  $desc[]=_('Impression du grand livre');$desc_long[]=_('Impression du grand livre');
$menu[]=_('Balance');  $desc[]=_('Impression des balances comptables');$desc_long[]=_('Impression des balances comptables');
$menu[]=_('Achat');  $desc[]=_('Menu achat');$desc_long[]=_('Regroupement pour les menus d\'achats(nouvelle opération, historique...)');
$menu[]=_('Menu et profil');  $desc[]=_('Menu ');$desc_long[]=_('Regroupement pour les menus et les profils');
$menu[]=_('Impression');  $desc[]=_('Menu impression');$desc_long[]=_('Menu impression');
$menu[]=_('Banque');  $desc[]=_('Information Banque');$desc_long[]=_('Regroupement des menus des journaux de trésorerie');
$menu[]=_('Grand\'Livre');  $desc[]=_('Grand livre analytique');$desc_long[]=_('Grand livre pour la comptabilité analytique');
$menu[]=_('Gestion');  $desc[]=_('Module gestion');$desc_long[]=_('Module gestion');
$menu[]=_('Lettrage');  $desc[]=_('Lettrage');$desc_long[]=_('Menu Lettrage');
$menu[]=_('Accueil');  $desc[]=_('Accueil');$desc_long[]=_('Choix de votre dossier');
$menu[]=_('Comptabilité');  $desc[]=_('Module comptabilité');$desc_long[]=_('Module comptabilité');
$menu[]=_('Divers');  $desc[]=_('Paramètres divers');$desc_long[]=_('Menu de différents paramètres');
$menu[]=_('Profil');  $desc[]=_('Configuration profil');$desc_long[]=_('Configuration des profils des utilisateurs, permet de fixer les journaux, profils dans les documents et stock que  ce profil peut utiliser. Cela limite les utilisateurs puisque ceux-ci ont un profil');
$menu[]=_('Poste');  $desc[]=_('Config. poste comptable de base');$desc_long[]=_('Config. poste comptable de base');
$menu[]=_('Fiche');  $desc[]=_('Liste,Balance,Historique par fiche');$desc_long[]=_('Permet d\'avoir la balance de toutes vos fiches, les résumés exportables en CSV, les historiques avec ou sans lettrages');
$menu[]=_('Préférence');  $desc[]=_('Préférence');$desc_long[]=_('Préférence de l\'utilisateur, apparence de l\'application pour l\'utilisateur, période par défaut et mot de passe');
$menu[]=_('Configuration étiquette');  $desc[]=_('Configuration des tags');$desc_long[]=_('Configuration des tags ou dossiers, on l\'appele tag ou dossier suivant la façon dont vous utilisez 
cette fonctionnalité. Vous pouvez en ajouter, en supprimer ou les modifier');
$menu[]=_('Balance croisée double');  $desc[]=_('Balance double croisées des imputations analytiques');$desc_long[]=_('Balance double croisées des imputations analytiques');
$menu[]=_('Sociétés');  $desc[]=_('Parametre societe');$desc_long[]=_('Information sur votre société : nom, adresse... utilisé lors de la génération de documents');
$menu[]=_('Période');  $desc[]=_('Gestion des périodes');$desc_long[]=_('Gestion des périodes : clôture, ajout de période, afin de créer des périodes vous pouvez aussi utiliser le plugin outil comptable');
$menu[]=_('Vérification ');  $desc[]=_('Vérification de la comptabilité');$desc_long[]=_('Vérifie que votre comptabilité ne contient pas d\'erreur de base, tels que l\'équilibre entre le passif et l\'actif, l\'utilisation des postes comptables...');
$menu[]=_('Ecriture Ouverture');  $desc[]=_('Ecriture d\'ouverture');$desc_long[]=_('Ecriture d\'ouverture ou écriture à nouveau, reporte les soldes des comptes de l\'année passé du poste comptable 0xxx à 5xxxx sur l\'année courante');
$menu[]=_('Document');  $desc[]=_('Config. modèle de document');$desc_long[]=_('Chargement de modèles de documents qui seront générés par NOALYSS, les formats utilisables sont libreoffice, html, text et rtf');
$menu[]=_('journaux');  $desc[]=_('Configuration des journaux');$desc_long[]=_('Création et modification des journaux, préfixe des pièces justificatives, numérotation, catégories de fiches accessibles à ce journal');
$menu[]=_('Sécurité');  $desc[]=_('configuration de la sécurité');$desc_long[]=_('Configuration de la sécurité, vous permet de donner un profil à vos utilisateurs, cela leur permettra d\'utiliser ce que vous souhaitez qu\'ils puissent utiliser');
$menu[]=_('Attribut de fiche');  $desc[]=_('Gestion des attributs de fiches ');$desc_long[]=_('Permet d\'ajouter de nouveaux attributs que vous pourrez par la suite ajouter à des catégories de fiches');
$menu[]=_('Etat des stock');  $desc[]=_('Etat des stock');$desc_long[]=_('Etat des stock de l\'exercice indiqué');
$menu[]=_('Modification Stocks');  $desc[]=_('Modification des stocks (inventaire)');$desc_long[]=_('Modification des stocks, menu utilisé pour l\'inventaire');
$menu[]=_('Histo. Changement');  $desc[]=_('Liste des changements manuels des stocks');$desc_long[]=_('Liste des changements manuels des stocks, inventaire, transfert de marchandises entre dépôts...');
$menu[]=_('Navigateur');  $desc[]=_('Menu simplifié pour retrouver rapidement un menu');$desc_long[]=_('Le navigateur vous présente une liste de menu auquel vous avez accès et vous permet d\'accèder plus rapidement au menu que vous souhaitez');
$menu[]=_('Recherche');  $desc[]=_('Recherche');$desc_long[]=_('Historique de toutes vos opérations dans tous  les journaux auquels vous avez accès, vous permettra de retrouver rapidement l\'opération qui vous intéresse sur base de la date, du poste comptable, des montants...');
$menu[]=_('Historique');  $desc[]=_('Historique');$desc_long[]=_('Historique de toutes vos opérations un menu de recherche, vous permettra de retrouver rapidement l\'opération qui vous intéresse');
$menu[]=_('Rapprochement');  $desc[]=_('Rapprochement bancaire');$desc_long[]=_('Permet de faire correspondre vos extraits bancaires avec les opérations de vente ou d\'achat, le lettrage se fait automatiquement');
$menu[]=_('Soldes');  $desc[]=_('Solde des comptes en banques, caisse...');$desc_long[]=_('Solde des journaux de trésorerie cela concerne les comptes en banques, caisse , les chèques... ');
$menu[]=_('Sortie &#9094');  $desc[]=_('Sortie');$desc_long[]=_('Déconnexion ');
$menu[]=_('Lettrage par Poste');  $desc[]=_('lettrage par poste comptable');$desc_long[]=_('lettrage par poste comptable');
$menu[]=_('Balance');  $desc[]=_('Balance par catégorie de fiche');$desc_long[]=_('Balance par catégorie de fiche ou pour toutes les fiches ayant un poste comptable');
$menu[]=_('Plan Comptable');  $desc[]=_('Config. du plan comptable');$desc_long[]=_('Modification de votre plan comptable, parfois il est plus rapide d\'utiliser le plugin "Poste Comptable"');
$menu[]=_('Historique vente');  $desc[]=_('Historique des ventes');$desc_long[]=_('Historique de toutes vos opérations dans les journaux de vente un menu de recherche, vous permettra de retrouver rapidement l\'opération qui vous intéresse');
$menu[]=_('Historique financier');  $desc[]=_('Historique financier');$desc_long[]=_('Historique de toutes vos opérations dans les journaux de trésorerie un menu de recherche, vous permettra de retrouver rapidement l\'opération qui vous intéresse');
$menu[]=_('Rapprochement');  $desc[]=_('Impression des rapprochements');$desc_long[]=_('Impression des rapprochements : opérations non rapprochées ou avec des montants différents');
$menu[]=_('Bilan');  $desc[]=_('Impression de bilan');$desc_long[]=_('Impression de bilan, ce module est basique, il est plus intéressant d\'utiliser le plugin "rapport avancés"');
$menu[]=_('Configuration des dépôts');  $desc[]=_('Configuration dépôts');$desc_long[]=_('Configuration des entrepots de dépôts');
$menu[]=_('Stock');  $desc[]=_('Stock');$desc_long[]=_('Permet d\'ajouter de nouvelles catégorie de fiche, d\'ajouter des attributs à ces catégories (numéro de téléphone, gsm, email...)');
$menu[]=_('Catégorie de fiche');  $desc[]=_('Gestion catégorie de fiche');$desc_long[]=_('Permet de changer le poste comptable de base des catégories de fiches');
$menu[]=_('Fiche');  $desc[]=_('Configuration de catégorie de fiches');$desc_long[]=_('Permet d\'ajouter de nouvelles catégorie de fiche, d\'ajouter des attributs à ces catégories (numéro de téléphone, gsm, email...)');
$menu[]=_('Etat des documents');  $desc[]=_('Etat des documents');$desc_long[]=_('Permet d\'ajouter des état pour les documents utilisés dans le suivi (à faire, à suivre...)');
$menu[]=_('Opérations diverses');  $desc[]=_('Menu opérations diverses');$desc_long[]=_('Regroupement pour les menus d\'opérations diverses (nouvelle opération, historique...)');
$menu[]=_('Impression Journaux');  $desc[]=_('Impression des journaux');$desc_long[]=_('Impression des journaux avec les détails pour les parties privés, la TVA et ce qui est non déductibles en ce qui concerne les journaux de vente et d\'achat');
$menu[]=_('Vente / Recette');  $desc[]=_('Menu ventes et recettes');$desc_long[]=_('Regroupement des menus ventes et recettes');
$menu[]=_('Impression');  $desc[]=_('Impression compta. analytique');$desc_long[]=_('Impression compta. analytique');
$menu[]=_('Compta Analytique');  $desc[]=_('Module comptabilité analytique');$desc_long[]=_('Module comptabilité analytique');
$menu[]=_('Tableau de bord');  $desc[]=_('Tableau de bord');$desc_long[]=_('Tableau de suivi, vous permet de voir en un coup d\'oeil vos dernières opérations, un petit calendrier, une liste de chose à faire...');
$menu[]=_('Avancé');  $desc[]=_('Menu avancé');$desc_long[]=_('Menu regroupant la création de rapport, la vérification de la comptabilité...');
$menu[]=_('Trésorerie');  $desc[]=_('Menu Financier');$desc_long[]=_('Regroupement pour les menus de trésorerie (nouvelle opération, historique...)');
$menu[]=_('Liste Suivi');  $desc[]=_('Document de suivi sous forme de liste');$desc_long[]=_('Liste de vos suivis, en fait de tous les documents, réunions ... dont vous avez besoin afin de suivre vos clients, fournisseurs ou administrations. Il permet la génération de documents comme les devis, les bordereau de livraison...');
$menu[]=_('Moyen de paiement');  $desc[]=_('Config. des méthodes de paiement');$desc_long[]=_('Configuration des moyens de paiements que vous voulez utiliser dans les journaux de type VEN ou ACH, les moyens de paiement permettent de générer l\'opération de trésorerie en même temps que l\'achat, la note de frais ou la vente');
$menu[]=_('Administration');  $desc[]=_('Suivi administration, banque');$desc_long[]=_('Suivi des administrations : courrrier, déclarations.');
$menu[]=_('Prévision');  $desc[]=_('Prévision');$desc_long[]=_('Prévision de vos achats, revenus, permet de suivre l\'évolution de votre société. Vos prévisions sont des formules sur les postes comptables et vous permettent aussi vos marges brutes.');
$menu[]=_('Export opérations rapprochées');  $desc[]=_('Export opérations rapprochées en CSV');$desc_long[]=_('');
$menu[]=_('Administrateur');  $desc[]=_('Suivi des gérants, administrateurs et salariés');$desc_long[]=_('Suivi de vos salariés, managers ainsi que des administrateurs, pour les documents et les opérations comptables');
$menu[]=_('Menu par défaut');  $desc[]=_('Configuration des menus par défaut');$desc_long[]=_('Configuration des menus par défaut, ces menus sont appelés par des actions dans d\'autres menus');
$menu[]=_('Agenda');  $desc[]=_('Agenda');$desc_long[]=_('Agenda, présentation du suivi sous forme d\'agenda ');
$menu[]=_('Export pièce PDF');  
$menu[]=_('Clef de répartition');  
$menu[]=_('Configuration extension');  
$menu[]=_('Favori &#9733 ');  $desc[]=_('Raccourci vers vos menus préférés');$desc_long[]=_('Ce menu vous présente  un menu rapide de vos menus préférés');
$menu[]=_('Balance agée');  $desc[]=_('Balance agée');$desc_long[]=_('Balance agée pour les clients et fournisseurs');
$menu[]=_('Export Balance agée');  $desc[]=_('Balance agée');$desc_long[]=_('Balance agée pour les clients et fournisseurs');
$menu[]=_('Exporte la pièce');  
$menu[]=_('Export le document');  
$menu[]=_('Exporte le modèle de document');  
?>
<?php 
$attr_def[]=_('Durée Amortissement');
$attr_def[]=_('Montant initial');
$attr_def[]=_('TVA non déductible');
$attr_def[]=_('TVA non déductible récupérable par l\'impôt');
$attr_def[]=_('Partie fiscalement non déductible');
$attr_def[]=_('Dépense  charge du grant (partie privé) ');
$attr_def[]=_('Compte bancaire');
$attr_def[]=_('Prix vente');
$attr_def[]=_('Prix achat');
$attr_def[]=_('Date début');
$attr_def[]=_('Nom');
$attr_def[]=_('Taux TVA');
$attr_def[]=_('Nom de la banque');
$attr_def[]=_('Description');
$attr_def[]=_('Personne de contact ');
$attr_def[]=_('numéro de tva ');
$attr_def[]=_('Adresse ');
$attr_def[]=_('pays ');
$attr_def[]=_('téléphone ');
$attr_def[]=_('email ');
$attr_def[]=_('Quick Code');
$attr_def[]=_('Ville');
$attr_def[]=_('Fax');
$attr_def[]=_('GSM');
$attr_def[]=_('code postal');
$attr_def[]=_('Numero de client');
$attr_def[]=_('Prénom');
$attr_def[]=_('Contrepartie pour TVA récup par impot');
$attr_def[]=_('Contrepartie pour TVA non Ded.');
$attr_def[]=_('Contrepartie pour dépense à charge du gérant');
$attr_def[]=_('Contrepartie pour dépense fiscal. non déd.');
$attr_def[]=_('Poste Comptable');
$attr_def[]=_('Date Fin');
$attr_def[]=_('Gestion stock');
$attr_def[]=_('Société');
?>
<?php 
$document_type[]=_('Document Interne');
$document_type[]=_('Bons de commande client');
$document_type[]=_('Bon de commande Fournisseur');
$document_type[]=_('Facture');
$document_type[]=_('Lettre de rappel');
$document_type[]=_('Courrier');
$document_type[]=_('Proposition');
$document_type[]=_('Email');
$document_type[]=_('Divers');
$document_type[]=_('Note de frais');
$document_type[]=_('Réception commande Fournisseur');
$document_type[]=_('Réception commande Client');
$document_type[]=_('Réception magazine');
?>
<?php 
$action[]=_('Ajout de fiche');
$action[]=_('Création, modification et effacement de fiche');
$action[]=_('création, modification et effacement de catégorie de fiche');
$action[]=_('Effacer les documents du suivi');
$action[]=_('Voir les documents du suivi');
$action[]=_('Modifier le type de document');
$action[]=_('Enlever une pièce justificative');
$action[]=_('Effacer une opération ');
$action[]=_('Partager une note');
$action[]=_('Créer une note publique');
$action[]=_('Effacer une note publique');
$mdp[]=_('Caisse');
$mdp[]=_('Paiement électronique');
$mdp[]=_('Caisse');
$mdp[]=_('Par gérant ou administrateur');
?>
<?php 
$jrn_def_name[]=_('Achat');
$jrn_def_name[]=_('Financier');
$jrn_def_name[]=_('Opération Diverses');
$jrn_def_name[]=_('Vente');
?>
<?php 
$jrn_def_description[]=_('Concerne tous les achats, factures reçues, notes de crédit reçues et notes de frais');
$jrn_def_description[]=_('Concerne tous les mouvements financiers (comptes en banque, caisses, visa...)');
$jrn_def_description[]=_('Concerne toutes les opérations comme les amortissements, les comptes TVA, ...');
$jrn_def_description[]=_('Concerne toutes les ventes, notes de crédit envoyées');
?>
<?php 
$jrn_type[]=_('Financier');
$jrn_type[]=_('Vente');
$jrn_type[]=_('Achat');
$jrn_type[]=_('Opérations Diverses');
?>
